version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=https://seb.unpak.ac.id
      - VITE_UPLOAD_URL=https://seb.unpak.ac.id/api/uploads
      - VITE_SELECT_URL=https://sipaksi.unpak.ac.id/select2
      - VITE_NODE_ENV=dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
