version: '3.8'

services:
  cbt_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://seb.unpak.ac.id
        VITE_UPLOAD_URL: https://seb.unpak.ac.id/api/uploads
        VITE_SELECT_URL: https://sipaksi.unpak.ac.id/select2
        VITE_NODE_ENV: dev
    container_name: cbt_frontend
    image: cbt_frontend:0.1.1
    security_opt:
      - "no-new-privileges:true"
      - apparmor=docker-default
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=https://seb.unpak.ac.id
      - VITE_UPLOAD_URL=https://seb.unpak.ac.id/api/uploads
      - VITE_SELECT_URL=https://sipaksi.unpak.ac.id/select2
      - VITE_NODE_ENV=dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
